### ISSUE TITLE
您好，Yunzai-Bot v3.0的lib目录下没有render.js，请问如何配置？

### ISSUE THREAD

**Issue by kikasyou** [zolay-poi/achievements-plugin#1]
![image](https://user-images.githubusercontent.com/77435538/185407295-154c1796-d920-42b2-a67d-106f2bcd0cfb.png)

**Comment by sjlei** [comment]
你好，不好意思，最近比较忙刚看到，v3版本云崽的配置教程，我这周末肝一下。

**Comment by sjlei** [comment]
v3最新版本已经加上`chromium_path`配置了，不用改js文件了，直接改配置就可以了。

将chrome路径填到`config/config/bot.yaml`配置文件下的`chromium_path`属性上即可。

--------

https://github.com/Le-niao/Yunzai-Bot/blob/660e583b78dfb4346e373c40e8c0f96eaeb42745/config/default_config/bot.yaml#L12-L13
