### ISSUE TITLE
TRSS Yunzai+Discord无法使用此插件

### ISSUE THREAD

**Issue by geol** [zolay-poi/achievements-plugin#13]
![299DF208-44EA-4E94-B436-7A7F3E6C0FDC](https://github.com/zolay-poi/achievements-plugin/assets/2117430/472ee34c-c5a3-4965-99c0-a29bda100d45)
同样的内容QQ上可以成功录入，但是Discord上不行。

**Comment by sjlei** [comment]
可能Discord的文件处理方式不一样，我有空了看一下

**Comment by geol** [comment]
> 可能Discord的文件处理方式不一样，我有空了看一下

好嘞，谢谢大佬！

**Comment by sjlei** [comment]
已修复，更新即可

**Comment by geol** [comment]
> 已修复，更新即可

太谢谢了！
