### ISSUE TITLE
大佬，原神3.0更新后成就列表没有更新，而且录入成就时一直显示椰羊启动失败

### ISSUE THREAD

**Issue by 6412111** [zolay-poi/achievements-plugin#2]

**Comment by sjlei** [comment]
最近比较忙…… 3.0 成就这周末加一下

椰羊启动失败，可能是服务器配置问题，也可能是没有配置chrome路径。

**Comment by sjlei** [comment]
最近比较忙…… 3.0 成就这周末加一下

椰羊启动失败，可能是服务器配置问题，也可能是没有配置chrome路径。

**Comment by sjlei** [comment]
3.0 的成就已经加上了，更新一下就好了
