### ISSUE TITLE
使用#成就查漏 全都是第一个人发的成就

### ISSUE THREAD

**Issue by jiexi22** [zolay-poi/achievements-plugin#3]
使用#成就查漏 全都是第一个人发的成就

**Comment by SleepyAsh0191** [comment]
`utils\common.js` 第 135 行改成 `let uid = await MysInfo.getUid(e);`

3.0兼容性目前貌似挺差
改完之后成就查漏能获取到uid，成就录入却不能了（貌似提交录屏也无回复）

**Comment by sjlei** [comment]
v3版本的云崽吗？看来兼容性还是有点问题，我抽空再系统完善和测试一下

**Comment by jiexi22** [comment]
v3版本 
utils\common.js 第 135 行改成 let uid = await MysInfo.getUid(e);之后 录入成就bot发送 绑定uid 已经绑定还是发送 绑定uid

**Comment by SleepyAsh0191** [comment]
> v3版本 utils\common.js 第 135 行改成 let uid = await MysInfo.getUid(e);之后 录入成就bot发送 绑定uid 已经绑定还是发送 绑定uid

等作者自己修吧（哭）

**Comment by sjlei** [comment]
问题已经修复了，V3云崽改了uid的获取方式，重新兼容了一下，更新下就好了
