### ISSUE TITLE
关于椰羊导入的问题

### ISSUE THREAD

**Issue by myd986** [zolay-poi/achievements-plugin#4]
大佬，我配置好了，可是导入椰羊的uiaf v1.1 json文件，机器人回复我`json文件内容错误：缺少必要字段gacha_type`，这是怎么回事呀，怎么解决呀？

**Comment by myd986** [comment]
<img width="824" alt="Screenshot 2022-09-19 at 11 07 33" src="https://user-images.githubusercontent.com/49913958/190943769-f6d32432-2811-44bc-ac95-3ebdca3a229c.png">

**Comment by sjlei** [comment]
这是和抽卡记录导入冲突了。
建议先看看成就录入帮助：https://docs.qq.com/doc/DWmVRSnRwRldzcm13
按照帮助里的步骤来操作。

![image](https://user-images.githubusercontent.com/34293221/190944299-6af47bb4-8e04-47ae-b4a0-105ab174618b.png)

**Comment by myd986** [comment]
谢谢大佬，不过使用“椰羊json”导入显示`UIAF格式的JSON文件尚未支持…`，要导入“椰羊json（旧）”。

**Comment by sjlei** [comment]
看来椰羊导出的格式他又改了，我抽空兼容一下
