### ISSUE TITLE
gitee登陆失败无法克隆

### ISSUE THREAD

**Issue by Msdyz123** [zolay-poi/achievements-plugin#5]
输入账号的时候没问题，接下来输入密码的时候控制台不显示输入的字符，回车后提示404notfound，应该是登录失败不让克隆，大佬们有解决办法嘛，或者有没有GitHub的链接啊

**Comment by sjlei** [comment]
什么意思？你这里不就是在github上提问的吗？而且公开项目不用登录就能clone啊

**Comment by Msdyz123** [comment]
> 什么意思？你这里不就是在github上提问的吗？而且公开项目不用登录就能clone啊

问题是GitHub上提供的克隆链接是gitee的，然后克隆的时候必须登录才行，控制台登录不让输入密码导致无法克隆

**Comment by sjlei** [comment]
> 问题是GitHub上提供的克隆链接是gitee的，然后克隆的时候必须登录才行，控制台登录不让输入密码导致无法克隆

把ee换成hub
